[workspace]
members = [
    "serio",
    "spansy",
    "mux/mux",
    "mux/test-harness",
    "websocket-relay",
    "futures-limit",
    "futures-plex",
    "web-spawn",
    "rand06-compat",
    "rangeset",
    "rangeset/fuzz",
]
resolver = "3"

[workspace.dependencies]
futures-plex = { path = "futures-plex" }
serio = { path = "serio" }
spansy = { path = "spansy" }
tlsn-mux = { path = "mux/mux" }
rangeset = { path = "rangeset" }

async-trait = "0.1"
bincode = "1.3"
bytes = "1"
cfg-if = "1"
criterion = "0.8"
futures = "0.3"
futures-channel = "0.3"
futures-core = "0.3"
futures-io = "0.3"
futures-sink = "0.3"
futures-util = "0.3"
pin-project-lite = "0.2"
pollster = "0.4"
rand = "0.10"
rand_core = { version = "0.10", default-features = false }
rand_core_06 = { package = "rand_core", version = "0.6", default-features = false }
rayon = "1"
serde = "1"
thiserror = "2"
tokio = "1.23"
tokio-serde = "0.8"
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release.package.rangeset-fuzz]
debug = 1
