[package]
name = "rand06-compat"
version = "0.2.0"
edition = "2024"
authors = ["TLSNotary Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tlsnotary/tlsn-utils"
description = "Compatibility wrapper between `rand_core` 0.6 and 0.10"
keywords = ["rand_core", "rand", "compat", "compatibility"]

[features]
default = ["std"]
std = ["rand_core_06/std"]

[dependencies]
rand_core = { version = "0.10", default-features = false }
rand_core_06 = { package = "rand_core", version = "0.6", default-features = false }

[dev-dependencies]
rand_core = "0.10"
rand = "0.10"
